<?php
/**
 * Created by IntelliJ IDEA.
 * User: nhancao
 * Date: 5/10/16
 * Time: 1:06 AM
 */
require_once dirname(__FILE__) . '/MBase.php';
require_once dirname(__FILE__) . '/MCustomer.php';
require_once dirname(__FILE__) . '/MProduct.php';
require_once dirname(__FILE__) . '/MShip.php';
require_once dirname(__FILE__) . '/MStock.php';
require_once dirname(__FILE__) . '/MTransaction.php';
require_once dirname(__FILE__) . '/MUser.php';